apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractly-grafana
  namespace: extractly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractly-grafana
  template:
    metadata:
      labels:
        app: extractly-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: extractly-secrets
              key: grafana-password
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: extractly
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://extractly-prometheus:9090
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: extractly
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'extractly'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
  extractly-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Extractly AI Platform",
        "tags": ["extractly"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total[5m])",
                "legendFormat": "Requests/sec"
              }
            ]
          },
          {
            "id": 2,
            "title": "Response Time",
            "type": "graph", 
            "targets": [
              {
                "expr": "histogram_quantile(0.95, http_request_duration_seconds_bucket)",
                "legendFormat": "95th percentile"
              }
            ]
          },
          {
            "id": 3,
            "title": "Pod CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{pod=~\"extractly-app-.*\"}[5m])",
                "legendFormat": "{{ pod }}"
              }
            ]
          },
          {
            "id": 4,
            "title": "Pod Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_usage_bytes{pod=~\"extractly-app-.*\"}",
                "legendFormat": "{{ pod }}"
              }
            ]
          }
        ]
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: extractly-grafana
  namespace: extractly
spec:
  selector:
    app: extractly-grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000