apiVersion: v1
kind: ServiceAccount
metadata:
  name: extractly-monitor
  namespace: extractly
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extractly-monitor
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extractly-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extractly-monitor
subjects:
- kind: ServiceAccount
  name: extractly-monitor
  namespace: extractly
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractly-prometheus
  namespace: extractly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractly-prometheus
  template:
    metadata:
      labels:
        app: extractly-prometheus
    spec:
      serviceAccountName: extractly-monitor
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus/'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: extractly
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'extractly-app'
      static_configs:
      - targets: ['extractly-service:80']
      metrics_path: /metrics
      scrape_interval: 5s
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - extractly
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
---
apiVersion: v1
kind: Service
metadata:
  name: extractly-prometheus
  namespace: extractly
spec:
  selector:
    app: extractly-prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090