apiVersion: v1
kind: Namespace
metadata:
  name: extractly
  labels:
    name: extractly
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: extractly-quota
  namespace: extractly
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: extractly-limits
  namespace: extractly
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container